// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockMarketChannelValidators is an autogenerated mock type for the MarketChannelValidators type
type MockMarketChannelValidators struct {
	mock.Mock
}

type MockMarketChannelValidators_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarketChannelValidators) EXPECT() *MockMarketChannelValidators_Expecter {
	return &MockMarketChannelValidators_Expecter{mock: &_m.Mock}
}

// IsChannelExists provides a mock function with given fields: channelID
func (_m *MockMarketChannelValidators) IsChannelExists(channelID uuid.UUID) bool {
	ret := _m.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for IsChannelExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(channelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMarketChannelValidators_IsChannelExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsChannelExists'
type MockMarketChannelValidators_IsChannelExists_Call struct {
	*mock.Call
}

// IsChannelExists is a helper method to define mock.On call
//   - channelID uuid.UUID
func (_e *MockMarketChannelValidators_Expecter) IsChannelExists(channelID interface{}) *MockMarketChannelValidators_IsChannelExists_Call {
	return &MockMarketChannelValidators_IsChannelExists_Call{Call: _e.mock.On("IsChannelExists", channelID)}
}

func (_c *MockMarketChannelValidators_IsChannelExists_Call) Run(run func(channelID uuid.UUID)) *MockMarketChannelValidators_IsChannelExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelValidators_IsChannelExists_Call) Return(_a0 bool) *MockMarketChannelValidators_IsChannelExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMarketChannelValidators_IsChannelExists_Call) RunAndReturn(run func(uuid.UUID) bool) *MockMarketChannelValidators_IsChannelExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsMarketChannelExists provides a mock function with given fields: marketChannelID
func (_m *MockMarketChannelValidators) IsMarketChannelExists(marketChannelID uuid.UUID) bool {
	ret := _m.Called(marketChannelID)

	if len(ret) == 0 {
		panic("no return value specified for IsMarketChannelExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(marketChannelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMarketChannelValidators_IsMarketChannelExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMarketChannelExists'
type MockMarketChannelValidators_IsMarketChannelExists_Call struct {
	*mock.Call
}

// IsMarketChannelExists is a helper method to define mock.On call
//   - marketChannelID uuid.UUID
func (_e *MockMarketChannelValidators_Expecter) IsMarketChannelExists(marketChannelID interface{}) *MockMarketChannelValidators_IsMarketChannelExists_Call {
	return &MockMarketChannelValidators_IsMarketChannelExists_Call{Call: _e.mock.On("IsMarketChannelExists", marketChannelID)}
}

func (_c *MockMarketChannelValidators_IsMarketChannelExists_Call) Run(run func(marketChannelID uuid.UUID)) *MockMarketChannelValidators_IsMarketChannelExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelValidators_IsMarketChannelExists_Call) Return(_a0 bool) *MockMarketChannelValidators_IsMarketChannelExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMarketChannelValidators_IsMarketChannelExists_Call) RunAndReturn(run func(uuid.UUID) bool) *MockMarketChannelValidators_IsMarketChannelExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsMarketInstanceExists provides a mock function with given fields: instanceID
func (_m *MockMarketChannelValidators) IsMarketInstanceExists(instanceID uuid.UUID) bool {
	ret := _m.Called(instanceID)

	if len(ret) == 0 {
		panic("no return value specified for IsMarketInstanceExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(instanceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMarketChannelValidators_IsMarketInstanceExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMarketInstanceExists'
type MockMarketChannelValidators_IsMarketInstanceExists_Call struct {
	*mock.Call
}

// IsMarketInstanceExists is a helper method to define mock.On call
//   - instanceID uuid.UUID
func (_e *MockMarketChannelValidators_Expecter) IsMarketInstanceExists(instanceID interface{}) *MockMarketChannelValidators_IsMarketInstanceExists_Call {
	return &MockMarketChannelValidators_IsMarketInstanceExists_Call{Call: _e.mock.On("IsMarketInstanceExists", instanceID)}
}

func (_c *MockMarketChannelValidators_IsMarketInstanceExists_Call) Run(run func(instanceID uuid.UUID)) *MockMarketChannelValidators_IsMarketInstanceExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelValidators_IsMarketInstanceExists_Call) Return(_a0 bool) *MockMarketChannelValidators_IsMarketInstanceExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMarketChannelValidators_IsMarketInstanceExists_Call) RunAndReturn(run func(uuid.UUID) bool) *MockMarketChannelValidators_IsMarketInstanceExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsShareHolderExists provides a mock function with given fields: userID, marketChannelID
func (_m *MockMarketChannelValidators) IsShareHolderExists(userID uuid.UUID, marketChannelID uuid.UUID) bool {
	ret := _m.Called(userID, marketChannelID)

	if len(ret) == 0 {
		panic("no return value specified for IsShareHolderExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(userID, marketChannelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMarketChannelValidators_IsShareHolderExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsShareHolderExists'
type MockMarketChannelValidators_IsShareHolderExists_Call struct {
	*mock.Call
}

// IsShareHolderExists is a helper method to define mock.On call
//   - userID uuid.UUID
//   - marketChannelID uuid.UUID
func (_e *MockMarketChannelValidators_Expecter) IsShareHolderExists(userID interface{}, marketChannelID interface{}) *MockMarketChannelValidators_IsShareHolderExists_Call {
	return &MockMarketChannelValidators_IsShareHolderExists_Call{Call: _e.mock.On("IsShareHolderExists", userID, marketChannelID)}
}

func (_c *MockMarketChannelValidators_IsShareHolderExists_Call) Run(run func(userID uuid.UUID, marketChannelID uuid.UUID)) *MockMarketChannelValidators_IsShareHolderExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelValidators_IsShareHolderExists_Call) Return(_a0 bool) *MockMarketChannelValidators_IsShareHolderExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMarketChannelValidators_IsShareHolderExists_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) bool) *MockMarketChannelValidators_IsShareHolderExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMarketChannelValidators creates a new instance of MockMarketChannelValidators. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarketChannelValidators(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarketChannelValidators {
	mock := &MockMarketChannelValidators{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
