// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockMarketChannelValidator is an autogenerated mock type for the MarketChannelValidator type
type MockMarketChannelValidator struct {
	mock.Mock
}

type MockMarketChannelValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarketChannelValidator) EXPECT() *MockMarketChannelValidator_Expecter {
	return &MockMarketChannelValidator_Expecter{mock: &_m.Mock}
}

// IsMarketChannelExists provides a mock function with given fields: marketChannelID
func (_m *MockMarketChannelValidator) IsMarketChannelExists(marketChannelID uuid.UUID) bool {
	ret := _m.Called(marketChannelID)

	if len(ret) == 0 {
		panic("no return value specified for IsMarketChannelExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(marketChannelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMarketChannelValidator_IsMarketChannelExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMarketChannelExists'
type MockMarketChannelValidator_IsMarketChannelExists_Call struct {
	*mock.Call
}

// IsMarketChannelExists is a helper method to define mock.On call
//   - marketChannelID uuid.UUID
func (_e *MockMarketChannelValidator_Expecter) IsMarketChannelExists(marketChannelID interface{}) *MockMarketChannelValidator_IsMarketChannelExists_Call {
	return &MockMarketChannelValidator_IsMarketChannelExists_Call{Call: _e.mock.On("IsMarketChannelExists", marketChannelID)}
}

func (_c *MockMarketChannelValidator_IsMarketChannelExists_Call) Run(run func(marketChannelID uuid.UUID)) *MockMarketChannelValidator_IsMarketChannelExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelValidator_IsMarketChannelExists_Call) Return(_a0 bool) *MockMarketChannelValidator_IsMarketChannelExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMarketChannelValidator_IsMarketChannelExists_Call) RunAndReturn(run func(uuid.UUID) bool) *MockMarketChannelValidator_IsMarketChannelExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMarketChannelValidator creates a new instance of MockMarketChannelValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarketChannelValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarketChannelValidator {
	mock := &MockMarketChannelValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
