// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	models "github.com/hypebid/hypebid-app/pkg/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMarketChannelRepository is an autogenerated mock type for the MarketChannelRepository type
type MockMarketChannelRepository struct {
	mock.Mock
}

type MockMarketChannelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarketChannelRepository) EXPECT() *MockMarketChannelRepository_Expecter {
	return &MockMarketChannelRepository_Expecter{mock: &_m.Mock}
}

// CreateMarketChannel provides a mock function with given fields: marketChannel
func (_m *MockMarketChannelRepository) CreateMarketChannel(marketChannel *models.MarketChannel) (*models.MarketChannel, error) {
	ret := _m.Called(marketChannel)

	if len(ret) == 0 {
		panic("no return value specified for CreateMarketChannel")
	}

	var r0 *models.MarketChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.MarketChannel) (*models.MarketChannel, error)); ok {
		return rf(marketChannel)
	}
	if rf, ok := ret.Get(0).(func(*models.MarketChannel) *models.MarketChannel); ok {
		r0 = rf(marketChannel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MarketChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.MarketChannel) error); ok {
		r1 = rf(marketChannel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMarketChannelRepository_CreateMarketChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMarketChannel'
type MockMarketChannelRepository_CreateMarketChannel_Call struct {
	*mock.Call
}

// CreateMarketChannel is a helper method to define mock.On call
//   - marketChannel *models.MarketChannel
func (_e *MockMarketChannelRepository_Expecter) CreateMarketChannel(marketChannel interface{}) *MockMarketChannelRepository_CreateMarketChannel_Call {
	return &MockMarketChannelRepository_CreateMarketChannel_Call{Call: _e.mock.On("CreateMarketChannel", marketChannel)}
}

func (_c *MockMarketChannelRepository_CreateMarketChannel_Call) Run(run func(marketChannel *models.MarketChannel)) *MockMarketChannelRepository_CreateMarketChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.MarketChannel))
	})
	return _c
}

func (_c *MockMarketChannelRepository_CreateMarketChannel_Call) Return(_a0 *models.MarketChannel, _a1 error) *MockMarketChannelRepository_CreateMarketChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMarketChannelRepository_CreateMarketChannel_Call) RunAndReturn(run func(*models.MarketChannel) (*models.MarketChannel, error)) *MockMarketChannelRepository_CreateMarketChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarketChannelByID provides a mock function with given fields: marketChannelID
func (_m *MockMarketChannelRepository) GetMarketChannelByID(marketChannelID uuid.UUID) (*models.MarketChannel, error) {
	ret := _m.Called(marketChannelID)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketChannelByID")
	}

	var r0 *models.MarketChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.MarketChannel, error)); ok {
		return rf(marketChannelID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.MarketChannel); ok {
		r0 = rf(marketChannelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MarketChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(marketChannelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMarketChannelRepository_GetMarketChannelByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarketChannelByID'
type MockMarketChannelRepository_GetMarketChannelByID_Call struct {
	*mock.Call
}

// GetMarketChannelByID is a helper method to define mock.On call
//   - marketChannelID uuid.UUID
func (_e *MockMarketChannelRepository_Expecter) GetMarketChannelByID(marketChannelID interface{}) *MockMarketChannelRepository_GetMarketChannelByID_Call {
	return &MockMarketChannelRepository_GetMarketChannelByID_Call{Call: _e.mock.On("GetMarketChannelByID", marketChannelID)}
}

func (_c *MockMarketChannelRepository_GetMarketChannelByID_Call) Run(run func(marketChannelID uuid.UUID)) *MockMarketChannelRepository_GetMarketChannelByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelRepository_GetMarketChannelByID_Call) Return(_a0 *models.MarketChannel, _a1 error) *MockMarketChannelRepository_GetMarketChannelByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMarketChannelRepository_GetMarketChannelByID_Call) RunAndReturn(run func(uuid.UUID) (*models.MarketChannel, error)) *MockMarketChannelRepository_GetMarketChannelByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarketChannelsByInstanceID provides a mock function with given fields: instanceId
func (_m *MockMarketChannelRepository) GetMarketChannelsByInstanceID(instanceId uuid.UUID) ([]models.MarketChannel, error) {
	ret := _m.Called(instanceId)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketChannelsByInstanceID")
	}

	var r0 []models.MarketChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.MarketChannel, error)); ok {
		return rf(instanceId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.MarketChannel); ok {
		r0 = rf(instanceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarketChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(instanceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarketChannelsByInstanceID'
type MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call struct {
	*mock.Call
}

// GetMarketChannelsByInstanceID is a helper method to define mock.On call
//   - instanceId uuid.UUID
func (_e *MockMarketChannelRepository_Expecter) GetMarketChannelsByInstanceID(instanceId interface{}) *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call {
	return &MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call{Call: _e.mock.On("GetMarketChannelsByInstanceID", instanceId)}
}

func (_c *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call) Run(run func(instanceId uuid.UUID)) *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call) Return(_a0 []models.MarketChannel, _a1 error) *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call) RunAndReturn(run func(uuid.UUID) ([]models.MarketChannel, error)) *MockMarketChannelRepository_GetMarketChannelsByInstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMarketChannelRepository creates a new instance of MockMarketChannelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarketChannelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarketChannelRepository {
	mock := &MockMarketChannelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
